app:
  name: "TaskFlow"
  version: "1.0.0"
  port: 8080
  mode: "development" # development, testing, production
  
# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "Aa13892349048!"
  database: "taskflow"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # 秒

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5

# JWT配置
jwt:
  secret: "super-secret-jwt-key-change-in-production"
  expire_hours: 24
  refresh_expire_hours: 168 # 7天

# 日志配置
log:
  level: "debug" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 7
  max_age: 30 # 天

# 文件上传配置
upload:
  max_size: 10485760 # 10MB
  allowed_types: ["jpg", "jpeg", "png", "pdf", "doc", "docx"]
  storage_path: "uploads"
  chunk_size: 1048576 # 1MB